# Model configuration presets
MODEL_CONFIGS = {
    "small": {
        "input_dim": 2560,
        "hidden_dim": 256,
        "n_heads": 8,
        "n_cross_layers": 2,
        "d_ff": 1024,
        "dropout": 0.1,
        "max_len": 900,
        "use_attention_pool": True,
        "use_rotary": True,
        "use_sigmoid_output": True,
    },
    "medium": {
        "input_dim": 2560,
        "hidden_dim": 512,
        "n_heads": 8,
        "n_cross_layers": 3,
        "d_ff": 2048,
        "dropout": 0.1,
        "max_len": 900,
        "use_attention_pool": True,
        "use_rotary": True,
        "use_sigmoid_output": True,
    },
    "large": {
        "input_dim": 2560,
        "hidden_dim": 768,
        "n_heads": 12,
        "n_cross_layers": 4,
        "d_ff": 3072,
        "dropout": 0.15,
        "max_len": 900,
        "use_attention_pool": True,
        "use_rotary": True,
        "use_sigmoid_output": True,
    },
}
